-- v(2024.05.23)
SELECT FLAVOR
FROM (
    SELECT FLAVOR, TOTAL_ORDER FROM JULY
    UNION ALL
    SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF
) AS combined_table
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC limit 3;