-- v(2024.05.08)
SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
from APPOINTMENT A
join DOCTOR D on D.DR_ID = A.MDDR_ID
join PATIENT P on P.PT_NO = A.PT_NO
where A.APNT_CNCL_YMD IS NULL and A.MCDP_CD='CS' and A.APNT_YMD like '2022-04-13%'
order by A.APNT_YMD;
